### ISSUE TITLE
Continuation indenting

### ISSUE THREAD

**Issue by birdy247** [bobsta63/netbeans-psr-formatting#10]
I formatted a php file in PHP sotrm, and it looked like this:

![image](https://cloud.githubusercontent.com/assets/6965315/16114212/055e6946-33b8-11e6-9845-ac77a6034e94.png)

I then opened it in netbeans with thsi plugin and formatted it and it looked like this:

![image](https://cloud.githubusercontent.com/assets/6965315/16114236/2282e83a-33b8-11e6-8710-e2552a63a2ed.png)

This then has the problem of making the end of my file look like this:

![image](https://cloud.githubusercontent.com/assets/6965315/16114265/39dbd51e-33b8-11e6-8e21-ee2dd77314b0.png)

Is there any way I can prevent this?  I tried reducing the continuation indentation to 0, but it doesnt seem the right thing to do.

Thanks

**Comment by allebb** [comment]
Yeah, this unfortunately along with the inability to format the namespace declaration is a limitation of NetBeans but I'm hoping that in the next release it will support these features and I can then get them added.
