### ISSUE TITLE
Not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by dmahesh22** [bobsta63/netbeans-psr-formatting#12]
I've followed the steps how you have suggested in Netbeans 8.1 and 8.2 in Ubuntu 14.04 but formatting styles are not applying.

**Comment by allebb** [comment]
Did you restart NetBeans after importing the settings?

JFYI (assuming you may not know) - this only works when you use the auto-formatting key combination (it's not automatic as you type), on a google search, for Linux this would be: CTRL+SHIFT+F

If it still doesn't work then I'm not sure what's going on :(

**Comment by dmahesh22** [comment]
IDE is restarted after importing and I know I've to use CTRL+SHIFT+F for auto-formatting.

In installation steps following point is there

"Under the Select options to import:, check the All check box and then click Ok and then Apply."

After importing, "Select Options" are showing empty. I hope something is missing in Ubuntu 14.04.

Thanks for reply.

**Comment by allebb** [comment]
Ok no problem, just checking ;) - I'll bring up a Ubuntu 14.04 VM and see if I can reproduce - I assume you're using Vanilla Ubuntu and not a remix? (eg. Ubuntu MATE)

I'm pretty sure this is going to be a Netbeans issues though...

**Comment by dmahesh22** [comment]
@allebb Ya, your right I'm using Vanilla Ubuntu and following are further details of OS

Linux mahesh 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And faced this issue in Netbeans 8.0.1 and 8.2. Attached screenshot of after uploading psr formatting zip, as of your doc's options should be display but those are not displaying.

Thanks.
![screenshot from 2016-12-01 13 53 45](https://cloud.githubusercontent.com/assets/1269618/20786718/aca1121e-b7cd-11e6-88f5-f1d7d7cfb803.png)

**Comment by dmahesh22** [comment]
@allebb Have you find time to look into this issue ?

**Comment by allebb** [comment]
No, sorry but I'll start downloading a Ubuntu image now and test this
evening.

**Comment by allebb** [comment]
Morning @dmahesh22, so I checked last night on Ubuntu 14.04.5 with Netbeans 8.2 and unfortunately for you all worked as expected and I was able to import the settings and format my code just fine..

If possible I would obviously recommend updating the version of the JDK you are running and possibly re-installing Netbeans and applying any patches.

I'll close this issue now as the problem would appear to be a local issue with your PC configuration/build.
