### ISSUE TITLE
Combine this repo with maniaplanet/netbeans-psr

### ISSUE THREAD

**Issue by ghost** [bobsta63/netbeans-psr-formatting#2]
There already is a repo doing just the same:

https://github.com/maniaplanet/netbeans-psr

I suggest contacting that author and see how both repo's can be combined to one awesome one. This will make it more clear for the users to know which one they should use.

Their issue: https://github.com/maniaplanet/netbeans-psr/issues/6

**Comment by allebb** [comment]
I'd prefer to maintain my own version, closing the issue as in my opinion it's not a big deal!
