### ISSUE TITLE
Namespace declaration on next line after opening tag.

### ISSUE THREAD

**Issue by allebb** [bobsta63/netbeans-psr-formatting#4]
Although technically the current implementation that is configured in release 1.0.0 of this Netbeans extension does not violate the PSR standards (as discussed here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/641) it has now been noted by a couple of people that it would be better to add it on a new line following the opening PHP tag `<?php`

So instead of:

``` php
<?php namespace MyNamespace;
```

It should be changed to:

``` php
<?php
namespace MyNamespace;
```

At present following my investigation there is a bug since Netbeans 8.0 which prevents this from being added, the bug is described here: https://netbeans.org/bugzilla/show_bug.cgi?id=243744

I will keep track on this bug and will implement this enhancement as soon as technically possible (when NetBeans implemented this functionality)

**Comment by internalsystemerror** [comment]
First off, thank you for taking the time to make this... Second, would it be easier to allow 1 blank space before the namespace declaration for now? I can see both sides to that, just thought I would suggest it as it's what I'm currently using.

**Comment by fititnt** [comment]
Same here. I added 1 blank line before `namespace`

**Comment by allebb** [comment]
Now added a single blank line before the namespace declaration, latest release can now be downloaded here guys: https://github.com/bobsta63/netbeans-psr-formatting/releases/tag/v1.0.1

Was hoping that with the release of NetBeans 8.1 yesterday that the ability to have it on the next line (as per the PSR) would be added to NetBeans but doesn't appear so.

Hopefully the new blank line will suffice for now :)
