### ISSUE TITLE
Documentation on settings

### ISSUE THREAD

**Issue by dynasource** [bobsta63/netbeans-psr-formatting#8]
hello!

nice to see that you've opened a git repo for this.
I am trying to figure out which settings you've adopted within you zip.

Perhabs you could elaborate in your readme for this?
This would also enable others to do suggestions for improvements / updates.

thanks!

**Comment by allebb** [comment]
No need to document the settings IMO, simply import the package and then check the new settings via. the NetBeans preferences. - Not sure what the benefit to me documenting these would be given that they are plain text in the source code anyway :)
