### ISSUE TITLE
Add a Netbeans zip in v1.0.1

### ISSUE THREAD

**Issue by marciodojr** [bobsta63/netbeans-psr-formatting#9]
Hi @bobsta63.

Could you provide a Netbeans zip **ready to import** in the release v1.0.1 as you did in v1.0.0?

If not, please add some information in the **Installation** section about the differences in import.

**Comment by allebb** [comment]
I will get it added :) - Not sure why I over looked it in the last release.

**Comment by allebb** [comment]
This has now been added and can be downloaded from: https://github.com/bobsta63/netbeans-psr-formatting/releases/download/v1.0.1/netbeans-psr-formatting_v1-0-1.zip
